### ISSUE TITLE
Quill SSO

### ISSUE THREAD

**Issue by jackcook** [HackMIT/playground#3]
### Summary

Right now, we assign people a unique ID every single time they join -- this doesn't give us any way to identify hackers. Ideally, people will sign into Playground with Quill SSO, allowing us to identify each hacker, and save their progress/location/etc each time they leave and re-join.

### Potential solution

Talk to Shirlyn 😛

**Comment by AishikNagar** [comment]
Hi! Thanks for open sourcing this amazing software!!

May I know to intergate Quill and the playground for authentication? When I start up Quill and playground on my localhost, I am directed into the quill dashboard instead of spawning into the playground. How do I configure the code so that playground opens after sso from quill on localhost?

**Comment by jackcook** [comment]
Hi @AishikNagar! Make sure to enable your Playground login URL (even if it's just http://localhost:3000 or something similar) as a whitelisted SSO URL in the Quill admin panel.

**Comment by AishikNagar** [comment]
> Hi @AishikNagar! Make sure to enable your Playground login URL (even if it's just http://localhost:3000 or something similar) as a whitelisted SSO URL in the Quill admin panel. If everything is working correctly, it should redirect you from the Quill login page back to Playground.

Thanks for the prompt response @jackcook ! If its not too much trouble, may I ask know which quill repo to use for SSO? I couldn't find the SSO functionality on the quill repo in techx and hackMIT accounts (meaning there was no option to whitelist a domain in the admin panel at all, and the backend didn't have the SSO code). If you could direct me to the updated quill repo/codebase, it'll be very helpful!

Thanks again!

**Comment by pshirlyn** [comment]
Hi @AishikNagar,

The SSO code is in this pull request on the main Quill repository: https://github.com/techx/quill/pull/93. I'll merge it in ASAP but in the meantime feel free to merge it into your fork.

**Comment by AishikNagar** [comment]
> Hi @AishikNagar,
> 
> The SSO code is in this pull request on the main Quill repository: https://github.com/techx/quill/pull/93. I'll merge it in ASAP but in the meantime feel free to merge it into your fork.
> 

Hey @pshirlyn ! Awesome, thanks for all the help, appreciate it!
